### PR TITLE
Add support to CBOR dataclasses for stringifying all keys

### PR DESCRIPTION
**Pull request by felixeriksson**

### CODE REVIEW

**Comment by felixeriksson** [comment]
Before merging: Also stringify maps inside reports. See e-mail from Robert Helgesson:

> Jag lyckades inte parsa snippet- och setting-rapporter med C++-biblioteket vi använder (nlohmann). Orsaken var att dessa innehåller datafält av typen "map[int, T]" vilket tyvärr inte stöds. Jag gjorde följande förändring i pyanura och det löste problemet. Iallafall för settings-rapporten men jag tror det också bör funka för snippet-rapporterna (kan testa i Hyllie på tisdag, den 26:e).

> diff --git a/anura/dataclasses_cbor.py b/anura/dataclasses_cbor.py
> index 9800019..f1bf302 100644
> --- a/anura/dataclasses_cbor.py
> +++ b/anura/dataclasses_cbor.py
> @ -24,9 +24,13 @@ def _make_default_encoder(string_keys=False):
>              for f in dataclasses.fields(inst):
>                  key = f.metadata.get("cbor_key", [f.name](http://f.name/))
>                  key = str(key) if string_keys else key
> \-                obj[key] = getattr(inst, [f.name](http://f.name/))
> \+                value = getattr(inst, [f.name](http://f.name/))
> \+                # Make sure dictionary values have string keys.
> \+                if string_keys and type(value) is dict:
> \+                    value = {str(k): v for k, v in value.items()}
> \+                obj[key] = value
>              encoder.encode(obj)
> \-    
> \+
>      return _default_encoder
>  
>  def _to_cbor(self, string_keys=False):

**Review by abxy — APPROVED** [review]
LGTM!

**Comment by abxy** [comment]
FWIW: This could have been accomplished without modifying the `to_cbor()` method by using `to_struct()` and then recursively stringifying the keys in the output before using cbor2 to finally encode them as CBOR.

**Comment by abxy** [comment]
```
def stringify_keys(obj):
    """
    >>> stringify_keys({1: 2})
    {'1': 2}
    >>> stringify_keys([{1: 2}])
    [{'1': 2}]
    >>> stringify_keys({1: {1: 2}})
    {'1': {'1': 2}}
    """
    if isinstance(obj, dict):
        return {str(k): stringify_keys(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [stringify_keys(v) for v in obj]
    else:
        return obj
        
        
import doctest
doctest.testmod()
```

**Comment by felixeriksson** [comment]
> FWIW: This could have been accomplished without modifying the `to_cbor()` method by using `to_struct()` and then recursively stringifying the keys in the output before using cbor2 to finally encode them as CBOR.

That's definitely an option. But perhaps it is a good addition to `cbor_dataclasses` that they can stringify keys? I'm not sure if the only-accept-string-keys behaviour is a peculiarity of only `nlohmann` or if other CBOR tools also have this limitation. If the latter is true, I would argue that it's a nice feature in pyanura.

**Comment by rycee** [comment]
The merged version seems to miss the recursive key stringification?

**Comment by felixeriksson** [comment]
> Thanks! But the merged version seems to miss the recursive key stringification?

You're right, now it's fixed :) https://github.com/ReVibe-Energy/pyanura/commit/5f789a4e658aee1af0cb930e6046e29ce949bd96

**Comment by rycee** [comment]
Great! Will try it out on Monday 🙂

**Pull request merged**
